FROM node:18.15.0

ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app

COPY package*.json ./

RUN npm install --save-dev nodemon
RUN npm install
RUN npm install cors

COPY . .

EXPOSE 8080

CMD ["npm", "run", "start:dev"]
